services:
  - type: web
    name: poke-backend-nodejs
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false

  - type: web
    name: anime-backend-python
    env: python
    rootDir: backend-python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: anime_db

  - type: web
    name: docentes-backend-nodejs
    env: node
    rootDir: backend-docentes
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false

  - type: static
    name: poke-movil-frontend
    rootDir: frontend
    buildCommand: npm install && npx expo export -p web
    staticPublishPath: ./dist
