/**
 * Semilla de Docentes de UNINPAHU (Facultad de Ingeniería y Tecnologías de la Información - FITI)
 */
const DOCENTES_INICIALES = [
  {
    id: 1,
    nombre: "ELFAR DIDIER MORANTES SANCHEZ",
    cargo: "Profesor Universitario e Instructor SENA | Arquitecto de Software",
    programa: "Ingeniería de Software",
    facultad: "Facultad de Ingeniería y Tecnologías de la Información (FITI)",
    correo: "emorantessa@uninpahu.edu.co",
    telefono: "+57 (601) 3323500 Ext. 192",
    sede: "Sede Principal Bogotá (Calle 44 # 16-20)",
    imagen: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80",
    linkedin: "https://www.linkedin.com/in/elfar-didier-morantes-s%C3%A1nchez/",
    resumen: "Ingeniero Electrónico | Magíster en Educación y Elearning | Profesor Universitario e Instructor SENA | Desarrollador de Software | Arquitecto de Software | Fullstack Web Developer.",
    perfil_completo: "ELFAR DIDIER MORANTES SÁNCHEZ es Ingeniero Electrónico y Magíster en Educación y Elearning. Cuenta con una destacada trayectoria académica y profesional como Profesor Universitario en UNINPAHU e Instructor SENA. En la industria del software se desempeña como Desarrollador Fullstack y Arquitecto de Software, especializado en diseño de sistemas distribuidos, microservicios agnósticos, computación en la nube, bases de datos relacionales (MySQL, MariaDB, Oracle) y plataformas e-learning de alto impacto pedagógico.",
    formacion: "Ingeniero Electrónico | Magíster en Educación y Elearning | Especialista en Ingeniería de Software y Arquitecturas Distribuidas",
    areas_investigacion: "Arquitectura de Software, Microservicios Agnósticos, Cloud Computing, Metodologías Ágiles, Plataformas E-Learning, Modelado y Optimización de Bases de Datos Relacionales (MySQL/MariaDB).",
    asignaturas: "Arquitectura de Software, Microservicios y APIs, Desarrollo Web Fullstack, Bases de Datos Relacionales (MySQL), Computación en la Nube, Programación Móvil."
  },
  {
    id: 2,
    nombre: "Jorge Jurado",
    cargo: "Docente Titular e Investigador FITI",
    programa: "Ingeniería de Software",
    facultad: "Facultad de Ingeniería y Tecnologías de la Información (FITI)",
    correo: "jjurado@uninpahu.edu.co",
    telefono: "+57 (601) 3323500 Ext. 192",
    sede: "Sede Principal Bogotá",
    imagen: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    linkedin: "https://www.linkedin.com/school/uninpahu/",
    resumen: "Docente destacado por excelencia pedagógica en la Facultad de Ingeniería y Tecnologías de la Información. Especialista en arquitectura de software y bases de datos relacionales.",
    perfil_completo: "Jorge Jurado es un destacado docente universitario e investigador con más de 12 años de trayectoria académica y profesional en la industria del software. Ha orientado asignaturas troncales en UNINPAHU, destacándose por su enfoque pragmático en patrones de diseño arquitectural y gobierno de datos relacionales.",
    formacion: "Magíster en Ingeniería de Sistemas y Computación - UNAL | Ingeniero de Sistemas - UNINPAHU",
    areas_investigacion: "Sistemas Distribuidos, Cloud Computing, Microservicios, Optimización de Bases de Datos Relacionales (MySQL / PostgreSQL).",
    asignaturas: "Arquitectura de Software, Microservicios y APIs, Computación en la Nube, Escalabilidad de Sistemas."
  },
  {
    id: 3,
    nombre: "Edgar Humberto Angel Millan",
    cargo: "Docente Líder del Área Multimedia y Ciberseguridad",
    programa: "Ingeniería de Software y Multimedia",
    facultad: "Facultad de Ingeniería y Tecnologías de la Información (FITI)",
    correo: "eangelm@uninpahu.edu.co",
    telefono: "+57 (601) 3323500 Ext. 192",
    sede: "Sede Principal Bogotá",
    imagen: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    linkedin: "https://www.linkedin.com/school/uninpahu/",
    resumen: "Docente líder del área multimedia y tecnologías emergentes. Experto en seguridad informática, desarrollo de videojuegos, interfaces inmersivas e inteligencia artificial.",
    perfil_completo: "Edgar Humberto Ángel Millán es pionero en la integración de entornos multimedia, ciberseguridad y modelos predictivos dentro del currículo de UNINPAHU. Cuenta con más de una década de experiencia docente liderando laboratorios de desarrollo y proyectos de innovación pedagógica.",
    formacion: "Especialista en Seguridad de la Información | Ingeniero de Sistemas y Multimedia | Diplomado en Deep Learning y Computer Vision",
    areas_investigacion: "Ciberseguridad en APIs y Microservicios, Procesamiento Digital de Imágenes, Redes Neuronales Artificiales, Computación Gráfica Interactiva.",
    asignaturas: "Seguridad Informática, Desarrollo de Videojuegos, Inteligencia Artificial Básica, Computación Gráfica, Práctica Profesional."
  },
  {
    id: 4,
    nombre: "Lotus King Salcedo Vallejo",
    cargo: "Docente Investigador y Líder de Semilleros",
    programa: "Ingeniería de Software",
    facultad: "Facultad de Ingeniería y Tecnologías de la Información (FITI)",
    correo: "lsalcedov@uninpahu.edu.co",
    telefono: "+57 (601) 3323500 Ext. 192",
    sede: "Sede Principal Bogotá",
    imagen: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80",
    linkedin: "https://www.linkedin.com/school/uninpahu/",
    resumen: "Líder del grupo de investigación y semilleros en lógica computacional, epistemología aplicada y fundamentación ética de sistemas inteligentes.",
    perfil_completo: "Lotus King Salcedo Vallejo se distingue por su enfoque riguroso en los fundamentos teóricos y matemáticos de la computación. En UNINPAHU orienta a los estudiantes en la formulación de hipótesis científicas, diseño de algoritmos de alta eficiencia y análisis de impacto ético en sistemas autónomos.",
    formacion: "Doctorado en Filosofía de la Ciencia (Candidato) | Magíster en Ciencias de la Computación | Filósofo e Ingeniero de Sistemas",
    areas_investigacion: "Epistemología de la Inteligencia Artificial, Lógicas No Clásicas, Complejidad Computacional, Minería de Datos Académica.",
    asignaturas: "Lógica de Programación, Estructuras de Datos y Algoritmos, Metodología de la Investigación, Seminario de Investigación Tecnológica."
  },
  {
    id: 5,
    nombre: "Claudia Patricia Cárdenas",
    cargo: "Directora Académica y Docente de Calidad de Software",
    programa: "Ingeniería de Software",
    facultad: "Facultad de Ingeniería y Tecnologías de la Información (FITI)",
    correo: "ccardenas@uninpahu.edu.co",
    telefono: "+57 (601) 3323500 Ext. 190",
    sede: "Sede Principal Bogotá",
    imagen: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
    linkedin: "https://www.linkedin.com/school/uninpahu/",
    resumen: "Especialista en aseguramiento de calidad de software (QA), acreditación curricular y gestión estratégica del talento tecnológico.",
    perfil_completo: "Claudia Patricia Cárdenas ha liderado procesos clave de acreditación curricular y renovación de registros calificados ante el Ministerio de Educación Nacional para UNINPAHU. Como docente, imparte estándares de calidad de software (ISO/IEC 25010), pruebas automatizadas y gobierno de Tecnologías de la Información.",
    formacion: "Magíster en Gestión de Calidad | Especialista en Auditoría de Sistemas | Ingeniera de Sistemas | Auditora Líder ISO 9001 / ISO 27001",
    areas_investigacion: "Métricas de Calidad de Software, Pruebas Automatizadas de APIs, Gestión del Talento TI, Acreditación Universitaria.",
    asignaturas: "Aseguramiento de Calidad de Software (QA), Pruebas y Validación de Sistemas, Auditoría de TI, Ética Profesional."
  },
  {
    id: 6,
    nombre: "Diego Fernando Cadena",
    cargo: "Docente de Desarrollo Web y Móvil",
    programa: "Ingeniería de Software",
    facultad: "Facultad de Ingeniería y Tecnologías de la Información (FITI)",
    correo: "dcadena@uninpahu.edu.co",
    telefono: "+57 (601) 3323500 Ext. 192",
    sede: "Sede Principal Bogotá",
    imagen: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80",
    linkedin: "https://www.linkedin.com/school/uninpahu/",
    resumen: "Docente de desarrollo frontend y móvil. Especialista en React Native, Expo, diseño de interfaces de usuario y consumo de microservicios REST.",
    perfil_completo: "Diego Fernando Cadena es apasionado por la enseñanza de tecnologías web y móviles de vanguardia en UNINPAHU. Cuenta con más de 8 años de experiencia en la creación de aplicaciones móviles escalables para el sector financiero y educativo. Promueve el desarrollo centrado en el usuario (UX/UI), la integración continua y el consumo eficiente de microservicios agnósticos en la nube.",
    formacion: "Especialista en Tecnologías Móviles | Ingeniero de Software | Certificado Google Associate Android Developer",
    areas_investigacion: "Experiencia de Usuario Móvil (Mobile UX), Patrones de Arquitectura Frontend, Integración de Microservicios Agnósticos, Optimización de Rendimiento en Dispositivos Móviles.",
    asignaturas: "Desarrollo Móvil Multiplataforma, Programación Web I, Taller de Lenguajes de Programación, Interacción Humano-Computador."
  }
];

module.exports = { DOCENTES_INICIALES };
